all:
	g++ -I ../../lib/boost_1_53_0 -g -c CachingSolver.cpp NoSuspectOneUnknownLikelihoodSolver.cpp NoSuspectThreeUnknownsLikelihoodSolver.cpp NoSuspectTwoUnknownsLikelihoodSolver.cpp OneSuspectNoUnknownsLikelihoodSolver.cpp OneSuspectOneUnknownLikelihoodSolver.cpp OneSuspectTwoUnknownsLikelihoodSolver.cpp LikelihoodSolver.cpp
